In [1]:
import numpy as np

In [19]:
def snail(s)

def grab(s, index, axis):
    if s.shape == (1,):
        return [], s
    if axis == 0:
        grabbed = s[index, :]
    elif axis == 1:
        grabbed = s[:, index]
    s = np.delete(s, index, axis)
    return np.rot90(s), grabbed

In [22]:
array = np.array([[1,2,3],
         [8,9,4],
         [7,6,5]])

In [24]:
len(array)

3

In [23]:
s, g = grab(array, 0, 0)
print(s)
print(g)

[[4 5]
 [9 6]
 [8 7]]
[1 2 3]


In [7]:
array[:, 0]

array([1, 8, 7])